title: Engineer | Developer | Doer
author: Sandeep Anil Kumar
email: sandeepkanil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Software Engineer at Yahoo! working on Flurry Analytics.
  I graduated from University of Illinois at Chicago majoring in
  Computer Science. I have 5 years of experience.

# social links
github_username:  sandeep-anilkumar

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
